apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: my-app
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: my-app
spec:
  containers:
    - name: httpd-container
      image: httpd:latest
      ports:
        - containerPort: 443




